include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable a few rules temporarily to reduce noise. Re‑enable and
    # address violations incrementally.
    public_member_api_docs: false
    lines_longer_than_80_chars: false