name: asante_typing
description: |
  Asante Typing – a web‑based typing tutor that combines the pedagogical
  approach of Klavaro with the lesson structure of QuickQWERTY. It uses a
  unified two‑pane layout with a persistent menu on the left and a guide or
  practice area on the right. Lessons are stored in JSON and can be extended.

publish_to: 'none'
version: 0.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.0
  msix: ^3.16.12
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/units.json
    - assets/img/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

msix_config:
  display_name: Asante Typing
  publisher_display_name: Mukulu
  identity_name: org.mukulu.asante
  msix_version: 1.0.0.0
  logo_path: windows\runner\resources\AppIcon.ico
  architecture: x64