name: asante_typing
description: Asante Typing - unified layout, local image assets, tests, CI
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0
  dart_code_metrics: ^5.7.6

flutter:
  uses-material-design: true
  assets:
    - assets/units.json
    - assets/img/
