name: asante_typing
description: |
  Asante Typing – a web‑based typing tutor that combines the pedagogical
  approach of Klavaro with the lesson structure of QuickQWERTY. It uses a
  unified two‑pane layout with a persistent menu on the left and a guide or
  practice area on the right. Lessons are stored in JSON and can be extended.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/units.json
    - assets/img/

