name: asante_typing
description: Asante Typing - unified layout, local image assets, tests, CI
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0
  dart_code_metrics: ^5.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.0
  json_serializable: ^6.8.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/units.json
    - assets/img/
